[package]
name = "asic_art"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[[bin]]
name = "asic_art"
path = "src/main.rs"

[lib]
name = "asic_art_lib"
path = "src/lib.rs"

[dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "bmp", "tiff", "webp"] }
clap = { version = "4", features = ["derive"] }
terminal_size = "0.3"
video-rs = "0.11.0"
nokhwa = { version = "0.10.11", features = ["input-native"] }
ctrlc = "3.5.2"
scopeguard = "1.2.0"
rodio = "0.17"
crossterm = "0.29.0"
